version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      actions:
        patterns:
          - "*"
