name: bullying-detector-build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/*"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/bullying-detector-build.yaml"
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/')  }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Only Build
        if: ${{ ! startsWith(github.ref, 'refs/tags/')  }}
        uses: docker/build-push-action@v6
        with:
          platforms: "linux/amd64"
          push: false
      - name: Build and Push
        if: ${{ startsWith(github.ref, 'refs/tags/')  }}
        uses: docker/build-push-action@v6
        with:
          platforms: "linux/amd64"
          build-args: |
            APP_VERSION=${{ github.ref_name }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/bullying-detector:${{ github.ref_name }},${{ vars.DOCKERHUB_USERNAME }}/bullying-detector:latest
